get http://localhost:3000/players/

get http://localhost:3000/players/1/

put http://localhost:3000/players/2/
Content-type: application/json

{
  "playerName": "Raju"
}

get http://localhost:3000/matches/1/

get http://localhost:3000/players/3/matches/

get http://localhost:3000/matches/3/players/

get http://localhost:3000/players/3/playerScores/